// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsunheabapqwvhwrwvex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzdW5oZWFiYXBxd3Zod3J3dmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTk5NDQsImV4cCI6MjA2NjU3NTk0NH0.T8V9VmYwrz4uVRAyDNQkB0qsfs_WAWuAri4_vo3CAQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);